name: DadaGUIExamples
version: 2.7.0-SNAPSHOT
main: me.mrbast.dadagui.examples.DadaGuiExamplePlugin
author: MrBast
commands:
  dadagui:
    description: Opens the DadaGUI example menus.
    usage: /dadagui [static|player|shared|paged|vault|teamvault]
